work_unit/app/accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app.accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('additional_information/', views.additional_information,
         name='additional_information'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('initiate_interview_process/', views.initiate_interview_process,
         name='initiate_interview_process'),
    path('interview_process_success/', views.interview_process_success,
         name='interview_process_success'),
    path('my_interviews/', views.my_interviews, name='my_interviews'),
    path('interview_pairs/', views.interview_pairs, name='interview_pairs'),
    path('accounts/profile/upload_photo/',
         views.upload_photo, name='upload_photo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

work_unit/app/urls.py
from django.contrib import admin
from django.urls import path, include
from app.accounts.views import start_interview, add_tags, end_interview
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app.accounts.urls', namespace='accounts')),
    path('', include('app.work_unit.urls')),
    path('accounts/', include('allauth.urls')),
    path('start_interview/', start_interview, name='start_interview'),
    path('add_tags/', add_tags, name='add_tags'),
    path('end_interview/', end_interview, name='end_interview'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

work_unit/app/work_unit/urls.py
from django.urls import include, path
from . import views

app_name = 'work_unit'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('interviewer/', views.interviewer, name='interviewer'),
    path('interviewee/', views.interviewee, name='interviewee'),
    path('accounts/', include('app.accounts.urls', namespace='accounts')),
]

work_unit/app/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser, UserProfile, Interview


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password1', 'password2')


class ProfileImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image']

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ['category']
        fields = (
            'first_name', 'last_name', 'phone_number', 'participate', 'category',
            'legal_name', 'playa_name', 'staging_date', 'arrival_date', 'departure_date',
            'departure_staging_date', 'hash_id', 'arrival_staging_location',
            'departure_staging_location', 'ride_share_status', 'camp_score', 'work_unit',
            'work_unit_average', 'camp_class', 'profile_image'
        )


class AdminUserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'user', 'category', 'first_name', 'last_name', 'phone_number', 'participate',
            'legal_name', 'playa_name', 'staging_date', 'arrival_date', 'departure_date',
            'departure_staging_date', 'hash_id', 'arrival_staging_location',
            'departure_staging_location', 'ride_share_status', 'camp_score', 'work_unit',
            'work_unit_average', 'camp_class',
        )

# forms.py


class InterviewForm(forms.ModelForm):
    class Meta:
        model = Interview
        fields = ('interviewer',)


class MentionForm(forms.Form):
    mentioned_user = forms.ModelChoiceField(queryset=CustomUser.objects.all())
    count = forms.IntegerField(min_value=1)

work_unit/app/accounts/views.py
from django.shortcuts import render, redirect
from .forms import ProfileImageForm, CustomUserCreationForm, UserProfileForm
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth import login
from .models import CustomUser, UserProfile, Interview, InterviewMention
from allauth.account.utils import send_email_confirmation
from allauth.account.signals import email_confirmed
from django.dispatch import receiver
from django.contrib.auth.decorators import user_passes_test
from .forms import InterviewForm, MentionForm
from django.utils import timezone
import json, os
from django.contrib.auth.decorators import user_passes_test
from django.db import models
from PIL import Image
from django.core.files.storage import default_storage
from .models import get_profile_image_filename
from io import BytesIO
import base64
from django.core.files.base import ContentFile
from .models import AppConfig



def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.email = form.cleaned_data.get('email')
            user.save()
            # Send email confirmation
            send_email_confirmation(request, user)
            # Log the user in
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('accounts:additional_information')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def profile(request):
    user_profile = request.user.profile
    if request.method == 'POST':
        form = UserProfileForm(
            request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated successfully!')
            return redirect('accounts:profile')

    else:
        form = UserProfileForm(instance=user_profile)

    interviewee_first_name = ""
    interviewee_last_name = ""
    interviewer_first_name = ""
    interviewer_last_name = ""

    if request.user.profile.assigned_interviewee:
        interviewee_first_name = request.user.profile.assigned_interviewee.profile.first_name
        interviewee_last_name = request.user.profile.assigned_interviewee.profile.last_name

    if request.user.profile.assigned_interviewer:
        interviewer_first_name = request.user.profile.assigned_interviewer.profile.first_name
        interviewer_last_name = request.user.profile.assigned_interviewer.profile.last_name

    context = {
        'form': form,
        'interviewee_first_name': interviewee_first_name,
        'interviewee_last_name': interviewee_last_name,
        'interviewer_first_name': interviewer_first_name,
        'interviewer_last_name': interviewer_last_name,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def upload_photo(request):
    if request.method == 'POST':
        form = ProfileImageForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            profile = form.save(commit=False)
            image_data = request.POST.get('base64_image')
            image_data = image_data.split(',')[1]
            image = Image.open(BytesIO(base64.b64decode(image_data)))

            crop_x = int(round(float(request.POST.get('crop_x') or 0)))
            crop_y = int(round(float(request.POST.get('crop_y') or 0)))
            crop_width = int(round(float(request.POST.get('crop_width') or 0)))
            crop_height = int(
                round(float(request.POST.get('crop_height') or 0)))

            # Create a file name for the cropped image
            image_name = get_profile_image_filename(
                profile, 'cropped_image.webp')  # Change the file extension to .webp
            image_path = os.path.join('profile_pics', image_name)

            # Save the cropped image using default_storage
            with BytesIO() as buffer:
                # Change the format to 'WEBP'
                image.save(buffer, format='WEBP')
                buffer.seek(0)
                default_storage.save(image_path, buffer)

            profile.profile_image = image_path
            profile.save()
            messages.success(request, 'Profile photo uploaded successfully.')
            return redirect('accounts:profile')

        else:
            messages.error(request, 'Error uploading profile photo.')
            return redirect('accounts:upload_photo')

    else:
        form = ProfileImageForm(instance=request.user.profile)
        min_crop_dimension = AppConfig.objects.first().min_crop_dimension

    return render(request, 'accounts/upload_photo.html', {'form': form, 'min_crop_dimension': min_crop_dimension})


@login_required
def additional_information(request):
    user_profile, _ = UserProfile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user_profile)
        if form.is_valid():
            email = request.POST.get('email')  # Get the email from the request
            # Get the first name from the request
            first_name = request.POST.get('first_name')
            # Get the last name from the request
            last_name = request.POST.get('last_name')

            if CustomUser.objects.filter(email=email).exclude(pk=request.user.pk).exists():
                messages.error(
                    request, 'This email is already in use. Please use a different email address.')
            else:
                user_profile = form.save(commit=False)
                user_profile.user = request.user

                # Update the user's first name, last name, and email
                request.user.first_name = first_name
                request.user.last_name = last_name
                request.user.email = email

                request.user.save()
                user_profile.save()

                # Send the email confirmation
                send_email_confirmation(request, request.user)
                return HttpResponseRedirect(reverse('app.accounts:profile'))
    else:
        form = UserProfileForm(instance=user_profile)

    return render(request, 'accounts/additional_information.html', {'form': form})


@receiver(email_confirmed)
def email_confirmed_(request, email_address, **kwargs):
    user = email_address.user
    user.profile.category = 'member'
    user.profile.save()


def is_administrator(user):
    return user.is_authenticated and user.profile.category == 'administrator'


def admin_dashboard(request):
    users = CustomUser.objects.all()
    if request.method == 'POST':
        user_id = request.POST['user_id']
        new_category = request.POST['new_category']
        user = CustomUser.objects.get(pk=user_id)
        user.profile.category = new_category
        user.profile.save()
        messages.success(
            request, f"{user.username}'s category has been updated.")
        return redirect('accounts:admin_dashboard')

    is_admin = is_administrator(request.user)  # Add this line
    return render(request, 'accounts/admin_dashboard.html', {'users': users, 'is_admin': is_admin})

def start_interview(request):
    if request.method == 'POST':
        form = InterviewForm(request.POST)
        if form.is_valid():
            interviewed_users = request.POST.getlist('interviewed_users[]')
            interview = form.save(commit=False)
            interview.start_time = timezone.now()
            interview.save()
            for user_id in interviewed_users:
                user = CustomUser.objects.get(pk=user_id)
                mention, _ = InterviewMention.objects.get_or_create(
                    interview=interview, mentioned_user=user)
                mention.count += 1
                mention.save()
            return redirect('add_tags')
    else:
        form = InterviewForm(initial={'interviewer': request.user})

    users = CustomUser.objects.filter(
        profile__category='member', profile__participate=True)
    user_fullnames = [
        f"{user.first_name.strip()} {user.last_name.strip()}".strip() for user in users]

    user_fullnames_json = json.dumps(user_fullnames)

    assigned_interviewee = request.user.profile.assigned_interviewee

    return render(request, 'start_interview.html', {'form': form, 'user_fullnames_json': user_fullnames_json, 'assigned_interviewee': assigned_interviewee})


def end_interview(request):
    interview_id = request.session.get('interview_id')
    if interview_id:
        interview = Interview.objects.get(pk=interview_id)
        interview.end_time = timezone.now()
        interview.save()
        del request.session['interview_id']
    return redirect(reverse('app.accounts:profile'))


def add_tags(request):
    interview_id = request.session.get('interview_id')
    if not interview_id:
        return redirect('start_interview')

    if request.method == 'POST':
        form = MentionForm(request.POST)
        if form.is_valid():
            interview = Interview.objects.get(pk=interview_id)
            mentioned_user = form.cleaned_data['mentioned_user']
            count = form.cleaned_data['count']
            mention, created = InterviewMention.objects.get_or_create(
                interview=interview, mentioned_user=mentioned_user)
            mention.count += count
            mention.save()
            return redirect('add_tags')
    else:
        form = MentionForm()
    return render(request, 'add_tags.html', {'form': form})


@user_passes_test(is_administrator)
def initiate_interview_process(request):
    eligible_users = CustomUser.objects.annotate(
        is_member=models.Case(
            models.When(profile__category='member', then=models.Value(True)),

work_unit/templates/accounts/additional_information.html
{% extends "base.html" %}

{% block content %}
<h2>Additional Details</h2>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">First Name:</label>
        {{ form.first_name }}
    </div>
    <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
        {{ form.last_name }}
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" name="email" id="email" required />
    </div>
    <div class="form-group">
        <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
        {{ form.phone_number }}
    </div>
    <div class="form-group">
        <label for="{{ form.participate.id_for_label }}">Participate:</label>
        {{ form.participate }}
    </div>
    <button type="submit">Save</button>
</form>
{% endblock %}

work_unit/templates/accounts/admin_dashboard.html
{% extends 'base.html' %}

{% block content %}
<h1>Administrator Dashboard</h1>

{% if is_admin %}
<a href="{% url 'accounts:initiate_interview_process' %}" class="button">Initiate Interview Process</a>
<a href="{% url 'accounts:interview_pairs' %}">View Interview Pairs</a>

{% endif %}



<table>
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Category</th>
        <th>Change Category</th>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.profile.category }}</td>
        <td>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{ user.id }}">
                <select name="new_category">
                    <option value="member">Member</option>
                    <option value="removed_member">Removed Member</option>
                    <option value="camper">Camper</option>
                    <option value="observer">Observer</option>
                    <option value="administrator">Administrator</option>
                </select>
                <input type="submit" value="Update">
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

work_unit/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<h2>{{ user.profile.first_name }} {{ user.profile.last_name }}' Profile</h2>
{% if user.profile.category == "member" or user.profile.category == "administrator" %}
<h3>Actions</h3>
{% if interviewee_first_name and interviewee_last_name %}
<h4>Post Playa</h4>
<ul>
    <li>You are assigned to interview: <a
            href="{% url 'start_interview' %}?interviewee={{ user.profile.assigned_interviewee.id }}">{{ interviewee_first_name }} {{ interviewee_last_name }}</a></li>
    <li>You will be interviewed by: <a
            href="{% url 'start_interview' %}?interviewer={{ user.profile.assigned_interviewer.id }}">{{ interviewer_first_name }} {{ interviewer_last_name }}</a></li>
</ul>
<a href="{% url 'app.accounts:upload_photo' %}">Upload Profile Photo</a>

{% endif %}

<h3>Identity</h3>
<ul>
    <li>First Name: {{ user.profile.first_name }}</li>
    <li>Last Name: {{ user.profile.last_name }}</li>
    <li>Legal Name: {{ user.profile.legal_name }}</li>
    <li>Playa Name: {{ user.profile.playa_name }}</li>
    <li>Phone Number: {{ user.profile.phone_number }}</li>
    <li>Email: {{ user.email }}</li>
    <li>Hash ID: {{ user.profile.hash_id }}</li>
</ul>
<h3>Experience</h3>
<ul>
    <li>Camp Score: {{ user.profile.camp_score }}</li>
    <li>Work Unit: {{ user.profile.work_unit }}</li>
    <li>Work Unit Average: {{ user.profile.work_unit_average }}</li>
    <li>Years: </li>
</ul>
<h3>Logistics</h3>
<ul>
    <li>Staging Date: {{ user.profile.staging_date }}</li>
    <li>Arrival Date: {{ user.profile.arrival_date }}</li>
    <li>Departure Date: {{ user.profile.departure_date }}</li>
    <li>Departure Staging Date: {{ user.profile.departure_staging_date }}</li>
    <li>Arrival Staging Location: {{ user.profile.arrival_staging_location }}</li>
    <li>Departure Staging Location: {{ user.profile.departure_staging_location }}</li>
</ul>
{% endif %}
{% endblock %}

work_unit/templates/accounts/register.html
{% extends 'base.html' %}

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }} {{ form.errors }}
</div>
{% endfor %}
</div>
{% endif %}


{% block title %}
Register - {{ block.super }}
{% endblock %}

{% block content %}
<h1>Register a New Account</h1>
<form method="POST" action="{% url 'accounts:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

work_unit/templates/accounts/upload_photo.html
{% extends 'base.html' %}
{% load static %}
{% block extra_head %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css"
    crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}
{% block content %}

    <h2>Upload Profile Photo</h2>
    <form method="post" enctype="multipart/form-data" id="preview-form">
        {% csrf_token %}
        <input type="file" name="profile_image" id="id_profile_image" required>
        <button type="button" id="preview-button" disabled>Preview</button>
    </form>
    <div style="min-width: 300px; min-height: 300px;">
        <img id="image-preview" class="cropper-image" src="#" style="display:none;" alt="Image Preview">
    </div>
    <form method="post" enctype="multipart/form-data" id="upload-form" style="display:none;">
        {% csrf_token %}
        <input type="hidden" id="crop-x" name="crop_x" value="">
        <input type="hidden" id="crop-y" name="crop_y" value="">
        <input type="hidden" id="crop-width" name="crop_width" value="">
        <input type="hidden" id="crop-height" name="crop_height" value="">
        <input type="hidden" id="base64-image" name="base64_image" value="">
        <button type="submit">Upload</button>
    </form>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js" crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>
    <script>
        const inputImage = document.querySelector('#id_profile_image');
        const previewButton = document.querySelector('#preview-button');
        const imagePreview = document.querySelector('#image-preview');
        const uploadForm = document.querySelector('#upload-form');
        const cropX = document.querySelector('#crop-x');
        const cropY = document.querySelector('#crop-y');
        const cropWidth = document.querySelector('#crop-width');
        const cropHeight = document.querySelector('#crop-height');
        const base64Image = document.querySelector('#base64-image');
        let cropper;

        inputImage.addEventListener('change', (e) => {
            if (e.target.files && e.target.files[0]) {
                const file = e.target.files[0];
                const reader = new FileReader();

                reader.onload = (e) => {
                    imagePreview.src = e.target.result;
                };

                reader.readAsDataURL(file);
            }
        });

        imagePreview.addEventListener('load', () => {
            previewButton.disabled = false;
        });

        previewButton.addEventListener('click', () => {
            imagePreview.style.display = 'block';

            if (cropper) {
                cropper.destroy();
            }

            cropper = new Cropper(imagePreview, {
                aspectRatio: 1,
                viewMode: 1,
                minCropBoxWidth: "{{ min_crop_dimension| escapejs }}",
                minCropBoxHeight: "{{ min_crop_dimension| escapejs }}",
                crop: (event) => {
                    const { detail } = event;
                    const imageData = cropper.getImageData();
                    const scaleX = imageData.naturalWidth / imageData.width;
                    const scaleY = imageData.naturalHeight / imageData.height;

                    cropX.value = detail.x * scaleX;
                    cropY.value = detail.y * scaleY;
                    cropWidth.value = detail.width * scaleX;
                    cropHeight.value = detail.height * scaleY;
                },
                ready: function () {
                    // Set initial size of the cropping window to 300x300 pixels
                    const imageData = this.cropper.getImageData();
                    const containerData = this.cropper.getContainerData();
                    const scaleX = imageData.width / imageData.naturalWidth;
                    const scaleY = imageData.height / imageData.naturalHeight;
                    const initCropBoxWidth = "{{ min_crop_dimension| escapejs }}" * scaleX;
                    const initCropBoxHeight = "{{ min_crop_dimension| escapejs }}" * scaleY;

                    const initCropBoxData = {
                        width: initCropBoxWidth,
                        height: initCropBoxHeight,
                        left: (containerData.width - initCropBoxWidth) / 2,
                        top: (containerData.height - initCropBoxHeight) / 2,
                    };
                    this.cropper.setCropBoxData(initCropBoxData);
                },

            });


            uploadForm.style.display = 'block';
        });

        uploadForm.addEventListener('submit', (e) => {
            e.preventDefault();

            if (cropper) {
                cropper.getCroppedCanvas().toBlob((blob) => {
                    const reader = new FileReader();

                    reader.onload = (e) => {
                        base64Image.value = e.target.result;
                        uploadForm.submit();
                    };

                    reader.readAsDataURL(blob);
                }, 'image/webp');
            } else {
                alert('Please select and crop an image before uploading.');
            }
        });
    </script>

{% endblock %}

{% block extra_scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js" crossorigin="anonymous"
    referrerpolicy="no-referrer"></script>
{% endblock %}