work_unit/app/accounts/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app.accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('additional_information/', views.additional_information,
         name='additional_information'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('initiate_interview_process/', views.initiate_interview_process,
         name='initiate_interview_process'),
    path('interview_process_success/', views.interview_process_success,
         name='interview_process_success'),
    path('my_interviews/', views.my_interviews, name='my_interviews'),
    path('interview_pairs/', views.interview_pairs, name='interview_pairs'),
    path('accounts/profile/upload_photo/',
         views.upload_photo, name='upload_photo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

work_unit/app/urls.py
from django.contrib import admin
from django.urls import path, include
from app.accounts.views import start_interview, add_tags, end_interview
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app.accounts.urls', namespace='accounts')),
    path('', include('app.work_unit.urls')),
    path('accounts/', include('allauth.urls')),
    path('start_interview/', start_interview, name='start_interview'),
    path('add_tags/', add_tags, name='add_tags'),
    path('end_interview/', end_interview, name='end_interview'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

work_unit/app/work_unit/urls.py
from django.urls import include, path
from . import views

app_name = 'work_unit'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('interviewer/', views.interviewer, name='interviewer'),
    path('interviewee/', views.interviewee, name='interviewee'),
    path('accounts/', include('app.accounts.urls', namespace='accounts')),
]

work_unit/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}Default Title{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/sc_style.css' %}">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    {% block extra_head %}{% endblock %}
</head>

<body>
    <header>
        {% block header %}
        {% include 'navigation.html' %}
        {% endblock %}
    </header>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
    </div>
    {% endfor %}
    </div>
    {% endif %}

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        {% include 'navigation.html' %}
        <!-- Header content here -->
        {% block footer %}
        {% endblock %}
    </footer>

    <!-- Common JavaScript files -->
</body>

</html>

work_unit/templates/navigation.html
<div id="content">
    <div id="horz-list">
{% if user.is_authenticated %}
        <ul>
            <li><a href="/" class="button">Home</a></li>
            <li><a href="{% url 'accounts:logout' %}" class="button">Logout</a></li>
            <li><a href="{% url 'accounts:profile' %}" class="button">Profile</a></li>
{% else %}
            <li><a href="{% url 'accounts:login' %}" class="button">Login</a></li>
            <li><a href="{% url 'accounts:register' %}" class="button">Join SC</a></li>
{% endif %}
{% if user.profile.category == "administrator" %}
            <li><a href="{% url 'accounts:admin_dashboard' %}" class="button">Camp Leads</a></li>
{% endif %}
        </ul>
    </div>
</div>  

{% if user.is_staff %}
<ul>
    <li><a href="{% url 'admin:index' %}" class="button">Admin Dashboard</a></li>
</ul>
{% endif %}